apiVersion: v1
kind: Secret
metadata:
  name: env-vars
  namespace: catalog-api
type: Opaque
data:
  NODE_ENV: {{ .Values.env.NODE_ENV | b64enc }}
  PORT: {{ .Values.env.PORT | b64enc }}
  MONGO_USERNAME: {{ .Values.env.MONGO_USERNAME | b64enc }}
  MONGO_PASSWORD: {{ .Values.env.MONGO_PASSWORD | b64enc }}
  MONGO_PORT: {{ .Values.env.MONGO_PORT | b64enc }}
  MONGO_HOST: {{ .Values.env.MONGO_HOST | b64enc }}
  MONGO_DATABASE: {{ .Values.env.MONGO_DATABASE | b64enc }}
  API_URL: {{ .Values.env.API_URL | b64enc }}
  JWT_SECRET_KEY: {{ .Values.env.JWT_SECRET_KEY | b64enc }}
  SALT_ROUNDS: {{ .Values.env.SALT_ROUNDS | b64enc }}
  CONTRACT_SERVICE_ENDPOINT: {{ .Values.env.CONTRACT_SERVICE_ENDPOINT | b64enc }}
