apiVersion: v1
kind: Service
metadata:
  name: catalog-api
  namespace: catalog-api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: catalog-api
